import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Loader from "@/app/comp/loader"; // ✅ Import your client loader

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RB Portfolio",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Loader>{children}</Loader>
      </body>
    </html>
  );
}
